package model;
// Generated Feb 16, 2017 4:30:43 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Answers generated by hbm2java
 */
public class Answers  implements java.io.Serializable {


     private long answerId;
     private Questions questions;
     private Users users;
     private String content;
     private Date time;
     private Set<VoteAnswer> voteAnswers = new HashSet<VoteAnswer>(0);

    public Answers() {
    }

	
    public Answers(long answerId, Date time) {
        this.answerId = answerId;
        this.time = time;
    }
    public Answers(long answerId, Questions questions, Users users, String content, Date time, Set<VoteAnswer> voteAnswers) {
       this.answerId = answerId;
       this.questions = questions;
       this.users = users;
       this.content = content;
       this.time = time;
       this.voteAnswers = voteAnswers;
    }
   
    public long getAnswerId() {
        return this.answerId;
    }
    
    public void setAnswerId(long answerId) {
        this.answerId = answerId;
    }
    public Questions getQuestions() {
        return this.questions;
    }
    
    public void setQuestions(Questions questions) {
        this.questions = questions;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }
    public Set<VoteAnswer> getVoteAnswers() {
        return this.voteAnswers;
    }
    
    public void setVoteAnswers(Set<VoteAnswer> voteAnswers) {
        this.voteAnswers = voteAnswers;
    }




}


