package model;
// Generated Feb 16, 2017 4:30:43 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Long userId;
     private String name;
     private String email;
     private String password;
     private String avatar;
     private Set<VoteAnswer> voteAnswers = new HashSet<VoteAnswer>(0);
     private Set<Answers> answerses = new HashSet<Answers>(0);
     private Set<Questions> questionses = new HashSet<Questions>(0);
     private Set<VoteQuestion> voteQuestions = new HashSet<VoteQuestion>(0);

    public Users() {
    }

    public Users(String name, String email, String password, String avatar) {
        this.name = name;
        this.email = email;
        this.password = password;
        this.avatar = avatar;
    }

    public Users(String name, String email, String password, String avatar, Set<VoteAnswer> voteAnswers, Set<Answers> answerses, Set<Questions> questionses, Set<VoteQuestion> voteQuestions) {
       this.name = name;
       this.email = email;
       this.password = password;
       this.avatar = avatar;
       this.voteAnswers = voteAnswers;
       this.answerses = answerses;
       this.questionses = questionses;
       this.voteQuestions = voteQuestions;
    }
   
    public Long getUserId() {
        return this.userId;
    }
    
    public void setUserId(Long userId) {
        this.userId = userId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getAvatar() {
        return this.avatar;
    }
    
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }
    public Set<VoteAnswer> getVoteAnswers() {
        return this.voteAnswers;
    }
    
    public void setVoteAnswers(Set<VoteAnswer> voteAnswers) {
        this.voteAnswers = voteAnswers;
    }
    public Set<Answers> getAnswerses() {
        return this.answerses;
    }
    
    public void setAnswerses(Set<Answers> answerses) {
        this.answerses = answerses;
    }
    public Set<Questions> getQuestionses() {
        return this.questionses;
    }
    
    public void setQuestionses(Set<Questions> questionses) {
        this.questionses = questionses;
    }
    public Set<VoteQuestion> getVoteQuestions() {
        return this.voteQuestions;
    }
    
    public void setVoteQuestions(Set<VoteQuestion> voteQuestions) {
        this.voteQuestions = voteQuestions;
    }




}


