package model;
// Generated Feb 16, 2017 4:30:43 PM by Hibernate Tools 4.3.1



/**
 * VoteAnswer generated by hbm2java
 */
public class VoteAnswer  implements java.io.Serializable {


     private VoteAnswerId id;
     private Answers answers;
     private Users users;
     private long vote;

    public VoteAnswer() {
    }

    public VoteAnswer(VoteAnswerId id, Answers answers, Users users, long vote) {
       this.id = id;
       this.answers = answers;
       this.users = users;
       this.vote = vote;
    }
   
    public VoteAnswerId getId() {
        return this.id;
    }
    
    public void setId(VoteAnswerId id) {
        this.id = id;
    }
    public Answers getAnswers() {
        return this.answers;
    }
    
    public void setAnswers(Answers answers) {
        this.answers = answers;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public long getVote() {
        return this.vote;
    }
    
    public void setVote(long vote) {
        this.vote = vote;
    }




}


