package model;
// Generated Feb 16, 2017 4:30:43 PM by Hibernate Tools 4.3.1



/**
 * VoteAnswerId generated by hbm2java
 */
public class VoteAnswerId  implements java.io.Serializable {


     private long userId;
     private long answerId;

    public VoteAnswerId() {
    }

    public VoteAnswerId(long userId, long answerId) {
       this.userId = userId;
       this.answerId = answerId;
    }
   
    public long getUserId() {
        return this.userId;
    }
    
    public void setUserId(long userId) {
        this.userId = userId;
    }
    public long getAnswerId() {
        return this.answerId;
    }
    
    public void setAnswerId(long answerId) {
        this.answerId = answerId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VoteAnswerId) ) return false;
		 VoteAnswerId castOther = ( VoteAnswerId ) other; 
         
		 return (this.getUserId()==castOther.getUserId())
 && (this.getAnswerId()==castOther.getAnswerId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getUserId();
         result = 37 * result + (int) this.getAnswerId();
         return result;
   }   


}


